### ISSUE TITLE
OpenJDK fails to load class com.sun.imageio.plugins.jpeg.JPEGImageReader

### ISSUE THREAD

**Issue by bubbleguuum** [Optware/Optware-ng#126]
This was reported by a user using BubbleUPnP Server and image transcoding:
http://forum.xda-developers.com/showpost.php?p=67272679&postcount=11128

I can confirm that this class has a problem and it can be reprod with a simple main() with:

Class.forName("com.sun.imageio.plugins.jpeg.JPEGImageReader");

which outputs:

java.lang.UnsatisfiedLinkError: no jpeg in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1889)
	at java.lang.Runtime.loadLibrary0(Runtime.java:849)
	at java.lang.System.loadLibrary(System.java:1088)
	at sun.security.action.LoadLibraryAction.run(LoadLibraryAction.java:67)
	at sun.security.action.LoadLibraryAction.run(LoadLibraryAction.java:47)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.imageio.plugins.jpeg.JPEGImageReader.<clinit>(JPEGImageReader.java:89)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:195)

I suspect it cannot load libjpeg or something.

**Comment by alllexx88** [comment]
@bubbleguuum thanks for the report. This is fixed, but unfortunately the hosting server is full, so rsync to it fails, and the fixed version won't get to the feeds until it's freed up. Sorry about that. Reopening until the fixed version is online

**Comment by bubbleguuum** [comment]
Thank you for fixing this issue so fast !

**Comment by alllexx88** [comment]
@bubbleguuum You're welcome, and I will let you know when it's online :)

**Comment by alllexx88** [comment]
@bubbleguuum The fixed version is online. Please confirm that it works fine

**Comment by bubbleguuum** [comment]
I confirm that it works, thanks !

**Comment by alllexx88** [comment]
Great, thanks for the report
