### ISSUE TITLE
Pyload warning on startup after update

### ISSUE THREAD

**Issue by N0News** [Optware/Optware-ng#274]
Hi, after upgrading this packets i have warning on Pyload start/stop:
```
openssl from 1.0.2h-4 to 1.0.2n-1
libcurl from 7.55.0-2 to 7.58.0-2 
py27-curl from 7.21.5-4 to 7.21.5-5 
```
warning:
```
Stopping PyLoad
Traceback (most recent call last):
  File "pyLoadCore.py", line 48, in <module>
    from module.network.RequestFactory import RequestFactory
  File "/opt/share/pyload/module/network/RequestFactory.py", line 22, in <module>
    from Browser import Browser
  File "/opt/share/pyload/module/network/Browser.py", line 6, in <module>
    from HTTPRequest import HTTPRequest
  File "/opt/share/pyload/module/network/HTTPRequest.py", line 20, in <module>
    import pycurl
ImportError: pycurl: libcurl link-time ssl backend (openssl) is different from compile-time ssl backend (none/other)
Starting PyLoad
Traceback (most recent call last):
  File "pyLoadCore.py", line 48, in <module>
    from module.network.RequestFactory import RequestFactory
  File "/opt/share/pyload/module/network/RequestFactory.py", line 22, in <module>
    from Browser import Browser
  File "/opt/share/pyload/module/network/Browser.py", line 6, in <module>
    from HTTPRequest import HTTPRequest
  File "/opt/share/pyload/module/network/HTTPRequest.py", line 20, in <module>
    import pycurl
ImportError: pycurl: libcurl link-time ssl backend (openssl) is different from compile-time ssl backend (none/other)
```
Pyload seems to work ok, but wish to fix this.

**Comment by alllexx88** [comment]
Hi,

Thanks for the report. Please upgrade `py27-curl`, should be fixed now.

**Comment by N0News** [comment]
Yes, upgrading to py27-curl 7.21.5-6 helped. Thanks for quick help, now works like a charm
